# Generated by Django 3.0.4 on 2020-03-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0003_helper_available_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='age_requirement',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='hospital',
            name='number_of_helpers',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='hospital',
            name='skill_level',
            field=models.CharField(choices=[('1', 'BASIC'), ('2', 'INTERMEDIATE'), ('3', 'APPROBATION'), ('4', 'EXPERT')], default='1', max_length=1),
        ),
    ]
