# Generated by Django 3.0.4 on 2020-03-21 23:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Helper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('e_mail', models.CharField(max_length=200)),
                ('phone_nbr', models.CharField(max_length=25)),
                ('skill_level', models.CharField(choices=[('1', 'BASIC'), ('2', 'INTERMEDIATE'), ('3', 'APPROBATION'), ('4', 'EXPERT')], default='1', max_length=1)),
                ('post_code', models.CharField(max_length=25)),
                ('radius', models.IntegerField(default=50)),
                ('validated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('e_mail', models.CharField(max_length=200)),
                ('phone_nbr', models.CharField(max_length=25)),
                ('first_name_contact', models.CharField(max_length=200)),
                ('last_name_contact', models.CharField(max_length=200)),
                ('post_code', models.CharField(max_length=25)),
                ('street', models.CharField(max_length=200)),
                ('validated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_helpers', models.IntegerField()),
                ('skill_level', models.CharField(choices=[('1', 'BASIC'), ('2', 'INTERMEDIATE'), ('3', 'APPROBATION'), ('4', 'EXPERT')], default='1', max_length=1)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Hospital')),
            ],
        ),
    ]
