# Generated by Django 3.0.4 on 2020-03-21 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200321_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helper',
            name='radius',
            field=models.IntegerField(default=1000),
        ),
    ]
